apiVersion: v1                                                                                                                                                                                            
kind: Pod                                                                                                                                                                                                 
metadata:                                                                                                                                                                                                 
  name: postgres-client
spec:                                                                                                                                                                                                     
  containers:   
    - name: postgres-client
      image: postgres:16
      command: ["sleep", "infinity"]
